version: "3.9"
services:
  database:
    container_name: database
    build: ./database/
#    ports:
#      - 6060:5432
  api:
    container_name: api
    build: ./api/
    restart: always
    ports:
      - 80:8080
    links:
      - database
  anvilserver:
    container_name: AnvilServer
    build: ./anvil_backend/
    restart: always
    links:
      - api
