version: "3.9"
services:
  database:
    container_name: database
    build: ./database/
#    ports:
#      - 5432:5432
  api:
    container_name: api
    build: ./api/
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
#      - 80:8080
      - 443:5000
    links:
      - database
  anvilserver:
    container_name: AnvilServer
    build: ./anvil_backend/
    restart: always
    links:
      - api
